// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbXjgHx0keSUbctE2ul5Z7udqCzgE3lHY',
    appId: '1:207029773927:web:9dfebbede940e456fb16c2',
    messagingSenderId: '207029773927',
    projectId: 'trendy-markets',
    authDomain: 'trendy-markets.firebaseapp.com',
    storageBucket: 'trendy-markets.firebasestorage.app',
    measurementId: 'G-JHCQPPYFMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWxtINQU1QhF-HF8QRL0g9JT7__-Ocwo',
    appId: '1:207029773927:android:effbd54eabec0460fb16c2',
    messagingSenderId: '207029773927',
    projectId: 'trendy-markets',
    storageBucket: 'trendy-markets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZBG_7SIaGSY82U89n07QCsKvK62W3Qk',
    appId: '1:207029773927:ios:ad8a71fa431c22c7fb16c2',
    messagingSenderId: '207029773927',
    projectId: 'trendy-markets',
    storageBucket: 'trendy-markets.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZBG_7SIaGSY82U89n07QCsKvK62W3Qk',
    appId: '1:207029773927:ios:ad8a71fa431c22c7fb16c2',
    messagingSenderId: '207029773927',
    projectId: 'trendy-markets',
    storageBucket: 'trendy-markets.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbXjgHx0keSUbctE2ul5Z7udqCzgE3lHY',
    appId: '1:207029773927:web:2bde1e00a0659055fb16c2',
    messagingSenderId: '207029773927',
    projectId: 'trendy-markets',
    authDomain: 'trendy-markets.firebaseapp.com',
    storageBucket: 'trendy-markets.firebasestorage.app',
    measurementId: 'G-G6VCH316VJ',
  );

}